#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2019.2.0a5_f090fd076ca3"
#define UNITY_VERSION_FULL_NICE "2019.2.0a5 (f090fd076ca3)"
#define UNITY_VERSION_BLD 15765757
#define UNITY_VERSION_DATE 1556211665
#define UNITY_VERSION_WIN "2019.2.0.15765757"
#define UNITY_VERSION_BRANCH "graphics/raytracing/gdc2019"
