#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2019.2.0a5_fa79ef863c70"
#define UNITY_VERSION_FULL_NICE "2019.2.0a5 (fa79ef863c70)"
#define UNITY_VERSION_BLD 16415215
#define UNITY_VERSION_DATE 1553814428
#define UNITY_VERSION_WIN "2019.2.0.16415215"
#define UNITY_VERSION_BRANCH "graphics/raytracing/dxr"
